#! /bin/bash

set -e

echo 0 > /sys/kernel/debug/tracing/tracing_on
echo > /sys/kernel/debug/tracing/trace
echo 1 > /sys/kernel/debug/tracing/events/enable
echo "$1" > /sys/kernel/debug/tracing/buffer_size_kb
